apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-volume
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: gp2
  resources:
    requests:
      storage: 50Gi
